version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_UID=${UID}
        - APP_GID=${GID}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=password
    volumes:
      - .:/app
      - gem-cache:/usr/local/bundle

volumes:
  postgres-data:
  gem-cache:
